# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-55771-sebastian-MAX-L5/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/ALU.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Basys3_7SegmentMultiplexing.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Baud_gen.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Data_hazard_detection_unit.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Etapa_IF.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Etapa_MEM.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Forwarding_unit.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/IF_ID.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Instruction_decode.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/RAM.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/ROM.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/RX.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Registros.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/TX.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/etapa_ex.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/etapa_wb.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/latch_exmem.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/latch_idex.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/latch_memwb.v
      /home/sebastian/Documentos/TP3_ARQUI/TP3.srcs/sources_1/new/Top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-55771-sebastian-MAX-L5/realtime/Top_synth.xdc
    rt::sdcChecksum
    set rt::top Top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/sebastian/Documentos/TP3_ARQUI/TP3.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-55771-sebastian-MAX-L5/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
